### ISSUE TITLE
Instructions for Windows Cuda GPU Build

### ISSUE THREAD

**Issue by teddybear082** [empower-ai/empower-functions#6]
Not seeking help just figured this might be helpful to someone someday.  Not necessarily the only way but the way I got it working:

(1) create and activate virtual environment per default empower_functions instructions

(2) pip install empower_functions as per default instructions

(3) install Nvidia toolkit (I used cuda 12.1): https://developer.nvidia.com/cuda-12-1-1-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

(4) install Visual Studio with:
C++ CMake tools for Windows.
C++ core features

(5) run this command with the empower_functions virtual environment active in the Windows command prompt (command prompt, not powershell):
`set FORCE_CMAKE=1 && set CMAKE_ARGS=-DGGML_CUDA=on -DLLAMA_AVX=off -DLLAMA_AVX2=off -DLLAMA_FMA=off && pip install llama-cpp-python --no-cache-dir --force-reinstall --verbose`

That will take awhile but will overwrite the normal llama-cpp-python module with the Cuda support one.

(6) then run the server with the virtual environment active with a command like this:
`
python -m empower_functions.server --model C:\Github\empower-functions-gpu\models\ggml-model-Q4_K_M.gguf --chat_format empower-functions --port 8001 --n_ctx 8196 --n_gpu_layers 20`

replacing the path with the path where the model is saved on your computer and adjusting n_ctx to the desired context and n_gpu_layers to the amount of the layers to offload to the gpu.

**Comment by dyang415** [comment]
Thanks @teddybear082 ! Will include this into the README!
